### ISSUE TITLE
Y- andY+ dont work ?

### ISSUE THREAD

**Issue by Schnitzeltrauma** [Crayon2000/UsendMii-Client#10]
Hi
First of all i really appriciade your work 
i have the problem that left stick up and down dont work at all when i activate it on my new 2ds it glows orange so it is registered i guess but i´ve tried different execution (f.e. left stick up binded as right click or x-) but it just dont work.
sorry for my english :)

**Comment by Crayon2000** [comment]
Hello @Schnitzeltrauma, the GamePad API (required for Circle Pad and C Stick) is supported on:
* New Nintendo 3DS
* New Nintendo 3DS XL
* **New Nintendo 2DS XL**

Not on:
* Nintendo 3DS
* Nintendo 3DS XL
*  **Nintendo 2DS**

Source: https://en-americas-support.nintendo.com/app/answers/detail/a_id/13802/~/what-is-supported-by-the-internet-browser

So if you own a Nintendo 2DS, this will not work.
