### ISSUE TITLE
usendmii not working

### ISSUE THREAD

**Issue by loganlamothe** [Crayon2000/UsendMii-Client#12]
![IMG_2032](https://user-images.githubusercontent.com/41552330/87829456-21016d00-c84d-11ea-9dee-26d657a0edcd.JPG)
![IMG_2033](https://user-images.githubusercontent.com/41552330/87829462-22cb3080-c84d-11ea-8a61-c3b8e5d4e1d0.JPG)
IP is the same but port is not what I selected

**Comment by Crayon2000** [comment]
Make sure the port number is same in both applications. The default port is 4242, is there a reason to change it?

**Comment by loganlamothe** [comment]
also another problem the client wants 0.7.0 but I am using 0.8.0

**Comment by Crayon2000** [comment]
Those two versions should work together.

I guess the message should read: "Remember the program will not work without UsendMii 0.7.0 **(or newer)** running on your computer."

**Comment by Crayon2000** [comment]
If you really need to change the port number. There is currently no way to change it in UsendMii Client with the UI. But the _settings.ini_ file can be edited manually.
Simply change the port number to the value you need:
```ini
[server]
ipaddress=192.168.255.101
port=4243
```

**Comment by Crayon2000** [comment]
I will close this issue because I consider that UsendMii is working. The only thing I might change is the required version message in UsendMii Client.
