### ISSUE TITLE
freezes the wiiu when opend

### ISSUE THREAD

**Issue by Drqad** [Crayon2000/UsendMii-Client#16]
when i press load on homebrew 2.1 by dimark it just freezes my wii u 
my micro sd card is not in lock mode and i can't run the homebrew appstore lol

**Comment by Crayon2000** [comment]
Can you try with Homebrew Launcher 1.5: https://github.com/dimok789/homebrew_launcher/releases/tag/v1.5

If no homebrews are running, this problem seems unrelated to this application.
