### ISSUE TITLE
Wii U Pro controller support?

### ISSUE THREAD

**Issue by SwirlyStone5877** [Crayon2000/UsendMii-Client#17]
Is there any chance you can support the monstrosity known as the Wii U Pro controller?

**Comment by Crayon2000** [comment]
@SwirlyStone5877, I don't have Wii U Pro controller. If I add the support for this controller, will you be available for testing?

**Comment by SwirlyStone5877** [comment]
@Crayon2000 I will be available for testing. Let's just hope it won't brick my Wii U.

**Comment by SwirlyStone5877** [comment]
> @SwirlyStone5877, I don't have Wii U Pro controller. If I add the support for this controller, will you be available for testing?

You there, bud?

**Comment by Crayon2000** [comment]
Yes, I will need some time to make it work.

**Comment by SwirlyStone5877** [comment]
> Yes, I will need some time to make it work.

Got it. Sorry if I made it sound like I'm rushing you.

**Comment by Crayon2000** [comment]
@SwirlyStone5877, I have two questions.
1) Where you able to install MiisendU Wii U on your Wii U and make it work with UsendMii on your PC?
2) How many Wii U Pro controller do you own?

**Comment by SwirlyStone5877** [comment]
> @SwirlyStone5877, I have two questions.
> 
> 1. Where you able to install MiisendU Wii U on your Wii U and make it work with UsendMii on your PC?
> 2. How many Wii U Pro controller do you own?

1. I am able to install MiisendU with a computer, and UsendMii on my PC via the internet.
2. I have 1 Wii U pro controller.

**Comment by SwirlyStone5877** [comment]
> @SwirlyStone5877, I have two questions.
> 
> 1. Where you able to install MiisendU Wii U on your Wii U and make it work with UsendMii on your PC?
> 2. How many Wii U Pro controller do you own?

1. I am able to install MiisendU with a computer, and UsendMii on my PC via the internet.
2. I have 1 Wii U pro controller.

**Comment by Crayon2000** [comment]
@SwirlyStone5877, if you want to help test the feature. Here is a link to a version of MiisendU Wii U that support the Wii U Pro Controller: https://github.com/Crayon2000/MiisendU-Wii-U/suites/11038603331/artifacts/560653334

Here is the UsendMii release to use with this version: [UsendMii-WiiUPro.zip](https://github.com/Crayon2000/MiisendU-Wii-U/files/10824913/UsendMii-WiiUPro.zip)

I did some test with Cemu and I know that at least some part is working. I will continue to do some test on my side and may have time for an official release next week.

**Comment by SwirlyStone5877** [comment]
Thanks, will test when i get home.

**Comment by SwirlyStone5877** [comment]
I'm home and am currently testing. I will update as needed. Sorry for the long wait lol. Had to work overtime that night.

**Comment by Crayon2000** [comment]
Can you test that the analog sticks are working well. I think that Cemu does not set the Emulated Stick buttons.

**Comment by SwirlyStone5877** [comment]
AVG is giving me problems lol

**Comment by SwirlyStone5877** [comment]
there

**Comment by Crayon2000** [comment]
With the download or when running the executable?

**Comment by SwirlyStone5877** [comment]
with exe

**Comment by SwirlyStone5877** [comment]
tested and it works great. analog, dpad, and buttons work. no issues.

**Comment by SwirlyStone5877** [comment]
just make it to where avg isnt screaming in my face when i open it

**Comment by SwirlyStone5877** [comment]
all ports are good

**Comment by SwirlyStone5877** [comment]
couldnt test 4 tho. dont have that many wiimotes

**Comment by Crayon2000** [comment]
I will test that on Cemu emulator. It's OK, but not great:
![image](https://user-images.githubusercontent.com/11451841/221383963-d8a21421-3825-4a0b-b65b-61e7c9d42367.png)

**Comment by SwirlyStone5877** [comment]
great. works fine irl too

**Comment by SwirlyStone5877** [comment]
but theres one problem

**Comment by SwirlyStone5877** [comment]
m

**Comment by SwirlyStone5877** [comment]
wait nvm

**Comment by Crayon2000** [comment]
Thanks, I'll continue to do some more testing and do an official release pretty soon.

**Comment by SwirlyStone5877** [comment]
There's a bit of input lag, but other than that, it's all good.

**Comment by SwirlyStone5877** [comment]
Is it okay if I close this issue?

**Comment by SwirlyStone5877** [comment]
imma take that as a no

**Comment by Crayon2000** [comment]
You can close it, thanks for your help.

**Comment by SwirlyStone5877** [comment]
no problem
