### ISSUE TITLE
[request] support for other controllers?

### ISSUE THREAD

**Issue by Reual4412** [Crayon2000/UsendMii-Client#2]
Hey, this app is pretty good. However the lack of support for other controllers than the wiiu gamepad is a kind of a missed opportunity. could you add wiimote+classic controller pro and wiiu pro controller as supported devices?

**Comment by Tschebbischeff** [comment]
I definitely second this.
Trying to modify the code to use https://github.com/FIX94/libwupc atm. Total beginner with homebrew development though.

**Comment by Crayon2000** [comment]
I just want to mentioned that since version 0.7.0, Wii Remote controllers are supported in UsendMii (with Nunchuk and Classic Controller).

**Comment by MarioSonicLife** [comment]
I'm interested in this
Any chances of happening ?
