### ISSUE TITLE
web browser shut down.

### ISSUE THREAD

**Issue by aaaaaaaTheaaaaa** [Crayon2000/UsendMii-Client#29]
Nintendo shut down the Wii-U online services in April, and it seems to 3include the web browser. Maybe add a disclaimer that its down?

**Comment by Crayon2000** [comment]
I just tried the web browser and it still works. I'm pretty sure the web browser wasn't one of the various services that were shut down because it doesn't rely on external servers to function.

**Comment by Crayon2000** [comment]
Proof that it is still working:
![image (1)](https://github.com/user-attachments/assets/8985de0d-1cd1-4065-b2f7-847e0ffd3c5e)

**Comment by aaaaaaaTheaaaaa** [comment]
Every time I put in the URL it gives me an error code and every time I tried a keyword search it didn't work, so I assumed it was down. The browser is working on mine for loading other URL's, but the Usendmii URL wont load, giving me Error Code: 112-1028: Could not display page

**Comment by Crayon2000** [comment]
* Make sure you firewall or anti-virus is not blocking UsendMii server from working
* Make sure UsendMii is working by opening the url on your PC
* Make sure your PC and and Wii U are on the same network
