### ISSUE TITLE
PC not recognizing my computer [Homebrew]

### ISSUE THREAD

**Issue by SD-CD** [Crayon2000/UsendMii-Client#30]
The port numbers match up as well as the ip address but my computer does not recognize it as being connected. Is there a work around to this?

**Comment by Crayon2000** [comment]
1. Does the Wii U and your PC are on the same network?
2. Can you access Internet with your Wii U?
3. Did UsendMii gave you multiple IP Address, if so, did you tried them all?
4. Is UsendMii blocked by your firewall?

**Comment by SD-CD** [comment]
1. Yes
2. My WiiU can access the Internet and I have also tried using the internet method which did not work as well
3. Yes and I tried them all for the internet browser version. I think for the homebrew method I only tried two and left one behind.
4. I heard of people saying to this, but I am unsure of how to check. I'm on Windows 11.

**Comment by Crayon2000** [comment]
I'm pretty sure this is a networking issue. So if your Wii U and PC uses the same address network mask, ie: 192.168.x.y, they should be in the same network. Try to ping the Wii U from your PC and see if there is response.

**Comment by SD-CD** [comment]
How would I ping the Wii U from my PC? My address network mask would also be my IPv4 address, correct?

**Comment by Crayon2000** [comment]
Open a terminal and use the `ping` command with the IP address of your Wii U.

**Comment by SD-CD** [comment]
When I pinged it, it printed this four times: "Reply from 75.157.x.y: bytes=32 time<1ms TTL=128". The ip address isn't in the 192.168.x.y format, but that was my computer's ipv4 address and it was listed in usendmii.

**Comment by SD-CD** [comment]
Rereading your message, it seems that you were talking of the wii u's own ip address, not the one listed on usendmii. I get this message four times: "Reply from 64.114.x.x: Destination host unreachable." And now that I think of my internet, my computer is connected via an ethernet cable so could that be causing the issue?

**Comment by SD-CD** [comment]
Yes, using the ethernet cable was the problem. I do not believe I can use my ethernet cable at the same time due to how the wii u gamepad connects via wifi. Thank you for the help.
