### ISSUE TITLE
WiiU freezes after playing for half an hour

### ISSUE THREAD

**Issue by SD-CD** [Crayon2000/UsendMii-Client#31]
I am on the aroma environment and I downloaded this on the homebrew app store if that helps. I checked my sd card and both the .wuhb and .rpx versions of MiiSendU are installed on it. I have to manually turn off my wii u console then turn it back on each time the wii u gamepad freezes.

**Comment by Awesome-guyy** [comment]
I have the same issue here.

**Comment by Crayon2000** [comment]
Duplicate of #25
