### ISSUE TITLE
Server could not be started

### ISSUE THREAD

**Issue by ghost** [Crayon2000/UsendMii-Client#4]
Hi! I am trying to run the Mac OS 32 bit version, but it gives the following error.

`Server could not be started! Try changing the port number and click on Start again. Your firewall may also block this application.`

I know for a fact that I disabled my firewall, so I don't know what could be causing this.

Thanks!

**Comment by Crayon2000** [comment]
Hello, try to change the port number from 80 to 8080 (or something else that works). Often on macOS, port 80 is taken by iTunes.
