### ISSUE TITLE
8 direction Dpad

### ISSUE THREAD

**Issue by powerofgreed** [Crayon2000/UsendMii-Client#7]
![image](https://user-images.githubusercontent.com/33897592/46905085-d16b7000-cf07-11e8-8e44-f9388e0bb518.png)
Is there a way to make Continuous POV working for 45 degrees ?

**Comment by Crayon2000** [comment]
Hello, currently only the '4 directions POV Hat Switches' are supported. The 'Continuous' as only 4 directions. So it's not possible in the actual UsendMii version to do what you are asking.

I guess this feature could be done easily.

**Comment by Crayon2000** [comment]
Hello @powerofgreed, I have changed the code in UsendMii to use Continuous POV Hat Switches:
![usendmii_2018-10-15_21-18-03](https://user-images.githubusercontent.com/11451841/47016851-c9d1e400-d11e-11e8-91c7-0874fe0409fe.png)

So support for North-East, North-West, South-East and South-West was added.

Here is a link to a version for testing that the new feature is working correctly:
~~LINK REMOVED: UsendMii 0.6.1 is out~~

If it's OK, this issue could be close and I will do an official release of UsendMii 0.6.1.

**Comment by Crayon2000** [comment]
UsendMii 0.6.1 was released.

**Comment by powerofgreed** [comment]
u are the best  <3
